spring:
  application:
    name: vg-ms-enrollment
  data:
    mongodb:
      uri: mongodb+srv://admin:1234@mariaenriqueta.f47y4yu.mongodb.net/?retryWrites=true&w=majority&appName=MariaEnriqueta
      database: vg-ms-mariaenriqueta
  microservices:
    student:
      url: https://vg-ms-student-production-48e2.up.railway.app/api/v1/public/student
    attorney:
      url: https://vg-ms-attorney-v1-production.up.railway.app/api/v1/public/attorney
server:
  port: 8400
