spring:
  application:
    name: vg-ms-enrollment
  data:
    mongodb:
      uri: mongodb+srv://admin:1234@mariaenriqueta.f47y4yu.mongodb.net/?retryWrites=true&w=majority&appName=MariaEnriqueta
      database: vg-ms-mariaenriqueta
  microservices:
    student:
      url: http://localhost:8080/api/v1/public/student
    attorney:
      url: http://localhost:8083/attorney
server:
  port: 8400